20220310_flannel_issue

diff --git a/templates/k8s_bootstrap_master.template b/templates/k8s_bootstrap_master.template
--- a/templates/k8s_bootstrap_master.template
+++ b/templates/k8s_bootstrap_master.template
@@ -1,3 +1,24 @@
+#!/bin/bash
+run_cmd() {
+    retry=10
+    pause=60
+    attempt=0
+    echo "############################################################################################"
+    while [ $attempt -ne $retry ]; do
+      if eval "$@"; then
+        echo "$1 PASSED"
+        break
+      else
+        echo "$1 FAILED"
+      fi
+      ((attempt++))
+      sleep $pause
+      if [ $attempt -eq $retry ]; then
+        echo "$1 FAILED after $retry retries" | tee /tmp/cloudInitFailed.log
+        exit 255
+      fi
+    done
+}
 if_secondary_name=$(sudo dmesg | grep eth0 | tail -1 | awk -F' ' '{print $5}' | sed 's/://')
 sudo sed -i -e "s/if_name_secondary_to_be_replaced/"$if_secondary_name"/g" /tmp/50-cloud-init.yaml
 sudo cp /tmp/50-cloud-init.yaml ${net_plan_file}
